server:
  port: 8080
aws:
  region: us-west-2
  dynamo:
    endpoint:  http://localhost:8000/

cassandra:
  contactpoints: 127.0.0.1
  port: 9042
  keyspace: ks1
  basepackages: org.mddarr.providerservice.repository
  username: cassandra
  password: cassandra
  schema-action: NONE

